server:
  port: 8090
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rbenitec/rbenitez-config-data
          search-paths: .